package com.company.commands;

public enum CommandType {
    INFO, SHOW, ADD, UPDATE, REMOVE_BY_ID, CLEAR, SAVE, EXECUTE_SCRIPT,
    REMOVE_GREATER, REMOVE_LOWER, REORDER, AVERAGE_DISCOUNT, MIN_CREATION_DATE , PRINT_ASCENDING
}
